### ISSUE TITLE
Don't Worked with me :(

### ISSUE THREAD

**Issue by jottasystem** [notsapinho/puppeteer-extra-plugin-recaptcha-capmonster#1]
i did changes in project but it's continuing using 2recatpcha (provider old that i was using)

![Screen Shot 2022-03-07 at 23 25 55](https://user-images.githubusercontent.com/36551379/157154175-c25a4149-3ea6-4b06-9677-314d7e96fccf.png)
![Screen Shot 2022-03-07 at 23 27 52](https://user-images.githubusercontent.com/36551379/157154337-8fe2a445-6546-4dcc-aa2a-46d08341314c.png)

**Comment by notsapinho** [comment]
Which version of puppeteer-extra and puppeteer-extra-plugin-recaptcha are you using?

I just tested with puppeteer-extra@3.2.3 and puppeteer-extra-plugin-recaptcha@3.5.0 and looks fine
![image](https://user-images.githubusercontent.com/52896767/157298501-5c12534a-46a6-4eef-b20d-cd7a17162565.png)

**Comment by jottasystem** [comment]
> puppeteer-extra-plugin-recaptcha
![Screen Shot 2022-03-08 at 15 19 28](https://user-images.githubusercontent.com/36551379/157300884-2e2fcff2-ab4f-43e8-a061-3fb5dead0143.png)

I'm using the same version that you, do u know I need to do anything? or if have anything with my machine, for example cache i don't know....

**Comment by notsapinho** [comment]
Do you have discord? So I can examine this in a better way

**Comment by jottasystem** [comment]
> Do you have discord? So I can examine this in a better way

Yes, of course, my nick is: jottasystem

Thanks for help!

**Comment by notsapinho** [comment]
whats your #?

actually just add me is better `notsapinho#2975`

**Comment by jottasystem** [comment]
sorry i copied wrong

**Comment by notsapinho** [comment]
Somehow fixed, nothing related to the actual package.

**Comment by jottasystem** [comment]
Thanks! Worked!
